spring:
  application:
    name: cloudpulse-monitor
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  threads:
    virtual:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s
        cancelRunningFuture: true
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 100
        maxWaitDuration: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: ALWAYS
